apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-backup
  namespace: project
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pg-backup
            image: mullil/pg-backup:latest
            envFrom:
            - secretRef:
                name: pg-backup-secret

