apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
  namespace: project
data:
  SERVER_PORT: "3000"
  TODO_BACKEND_PORT: "3001"
  IMAGE_PATH: "/app/files/image.jpg"
  TIME_PATH: "/app/files/image.time"
  PICSUM_URL: "https://picsum.photos/1200"
  DATABASE_URL: postgres://user:secret@postgres-svc.project.svc.cluster.local:5432/mydatabase?sslmode=disable
