apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: mullil/project:1.12
          volumeMounts:
            - name: image-cache
              mountPath: /app/files
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: log-claim