apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: PROJECT/project
          volumeMounts:
            - name: image-cache
              mountPath: /app/files
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: project-configmap
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: project-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: PROJECT/todo-backend
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: project-configmap
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"