apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-image
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: mullil/log-output-writer:1.10
          volumeMounts:
          - name: shared-image
            mountPath: /app/files
        - name: log-output
          image: mullil/log_output:1.10
          volumeMounts:
            - name: shared-image
              mountPath: /app/files
