apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: mullil/log_output:4.1
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-configmap
                  key: MESSAGE
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /log-healthz
               port: 3000
      volumes:
        - name: config-volume
          configMap:
            name: log-configmap
            items:
              - key: information.txt
                path: information.txt
